namespace MiTutor.DataAccess
{
    public static class StoredProcedure
    {
        public const string LISTAR_ESPECIALIDAD = "ESP_ListarEspecialidades_Select";
        public const string ACTUALIZAR_ESPECIALIDAD = "ESP_ActualizarEspecialidad_Update";

        //PLAN DE ACCIÓN
        public const string LISTAR_PLAN_ACTIONS = "sp_GetActionPlans";
        public const string CREAR_ACTION_PLAN = "sp_InsertActionPlan";
        public const string OBTENER_ACTION_PLAN_X_ID = "sp_GetActionPlansById";
        public const string ACTUALIZAR_PLAN = "sp_UpdateActionPlan";
        public const string LISTAR_ACTION_PLAN_ALUMNO = "sp_GetActionPlansStudent";
        public const string ELIMINAR_ACTION_PLAN = "sp_DeleteActionPlan";

        //COMPROMISOS
        public const string LISTAR_COMMITMENT_X_ID_ACTION_PLAN = "sp_GetCommitmentsByActionPlanId";
        public const string INSERTAR_COMMITMENT = "sp_InsertCommitment";
        public const string ACTUALIZAR_COMMITMENT = "sp_UpdateCommitment";
        public const string DELETE_COMMITMENT = "sp_DeleteCommitment";     

        //PERSONA
        public const string CREAR_PERSONA = "PERSON_INSERTAR_INSERT";

        //ESTUDIANTE
        public const string CREAR_ESTUDIANTE = "STUDENT_INSERTAR_INSERT";
        public const string LISTAR_ESTUDIANTES = "STUDENT_LISTAR_LIST";
        public const string LISTAR_ESTUDIANTES_POR_PROGRAMA = "STUDENT_LISTARXTUTORINGPROGRAMXTUTOR_SELECT";
        public const string SELECCIONAR_ESTUDIANTE_X_ID = "STUDENT_SELECCIONAR_SELECT";

        public const string LISTAR_ESTUDIANTES_POR_PROGRAMA_TUTORIA = "STUDENT_LISTARXTUTORINGPROGRAM_SELECT";
        public const string LISTAR_ESTUDIANTES_POR_ID = "STUDENT_LISTAR_BY_ID";

        public const string LISTAR_TODO_ESTUDIANTE = "STUDENT_LISTAR_TODO";
        public const string EDITAR_ESTUDIANTE = "STUDENT_EDITAR_UPDATE";


        //USUARIO
        public const string CREAR_USUARIO = "USER_ACCOUNT_INSERTAR_INSERT";
        public const string LISTAR_USUARIOS = "USER_LISTAR_SELECT";
        public const string OBTENERINFO_USUARIO = "USER_OBTENERINFOUSUARIO_SELECT";
        public const string EDITAR_USUARIO = "USER_EDITAR_UPDATE";
        public const string ELIMINAR_USUARIO = "USER_BORRAR_DELETE";
        public const string LISTAR_USUARIOS_SIN_ALUMNOS = "USER_LISTAR_SIN_ALUMNOS";

        //FACULTAD
        public const string CREAR_FACULTAD = "FACULTY_INSERTAR_INSERT";
        public const string LISTAR_FACULTADES = "FACULTY_LISTAR_SELECT";
        public const string ELIMINAR_FACULTAD = "FACULTY_ELIMINAR_DELETE";
        public const string ACTUALIZAR_FACULTAD = "FACULTY_ACTUALIZAR_UPDATE";
        public const string LISTAR_FACULTADES_TODOS = "FACULTY_LISTAR_TODOS";

        //ESPECIALIDAD
        public const string CREAR_ESPECIALIDAD = "SPECIALTY_INSERTAR_INSERT";
        public const string LISTAR_ESPECIALIDADES = "SPECIALTY_LISTAR_SELECT";
        public const string ELIMINAR_ESPECIALIDAD = "SPECIALTY_ELIMINAR_DELETE";
        public const string LISTAR_ESPECIALIDAD_X_FACULTAD = "SPECIALTY_LISTAR_X_FACULTY";
        public const string MODIFICAR_ESPECIALIDAD = "SPECIALTY_ACTUALIZAR_UPDATE";
        public const string LISTAR_ESPECIALIDADESXNOMBRE = "SPECIALTY_LISTAR_X_NAME";

        //UNIDAD DE DERIVACION
        public const string CREAR_UNIDAD = "UNITDERIVATION_INSERTAR_INSERT";
        public const string LISTAR_UNIDADES = "UNITDERIVATION_LISTAR_LIST";
        public const string ELIMINAR_UNIDAD = "UNITDERIVATION_ELIMINAR_DELETE";
        public const string LISTAR_SUB_UNIDADES = "SUBUNIT_LISTAR_X_UNITDERIVATION";
        public const string ACTUALIZAR_UNIDAD = "UNITDERIVATION_ACTUALIZAR_UPDATE";
        public const string CREAR_SUBUNIDAD = "SUBUNIT_INSERTAR_INSERT";

        //TUTOR
        public const string CREAR_TUTOR = "TUTOR_INSERTAR_INSERT";
        public const string LISTAR_TUTORES = "TUTOR_LISTAR_SELECT";
        public const string LISTAR_TUTORES_TIPO = "TUTOR_LISTATIPO_SELECT";
        public const string SELECCIONAR_TUTOR_X_ID = "TUTOR_SELECCIONAR_X_ID_SELECT";
        public const string LISTAR_TUTORES_PROGRAM = "TUTOR_PROGRAM_LISTAR_SELECT";
        public const string LISTAR_TUTORES_PROGRAM_ALUMNO = "TUTOR_LISTARXIDPROGRAM";
        public const string LISTAR_TUTORES_PROGRAM_VARIABLE = "TUTOR_LISTARXIDPROGRAMVARIABLE";

        //TUTORIA PROGRAM
        public const string CREAR_PROGRAMA_DE_TUTORIA = "TUTORINGPROGRAM_INSERTAR_INSERT";
        public const string LISTAR_PROGRAMA_DE_TUTORIA = "TUTORINGPROGRAM_LISTAR_LIST";
        public const string PROGRAMATUTORIA_ELIMINAR_ESTUDIANTES = "TUTORINGPROGRAM_DELETESTUNDENTS_DELETE";
        public const string LISTAR_PROGRAMA_POR_TUTOR = "TUTORINGPROGRAM_LISTARXTUTOR_SELECT";
        public const string LISTAR_PROGRAMA_POR_TIPOUSUARIO = "TUTORINGPROGRAM_LISTARXTIPOUSUARIO_SELECT";
        public const string LISTAR_PROGRAMA_POR_ALUMNO = "TUTORINGPROGRAM_LISTARXALUMNO_SELECT";
        public const string ELIMINAR_PROGRAMATUTORIA = "TUTORINGPROGRAM_BORRARPROGRAMA_DELETE";
         
        //PROGRAMA-TUTOR-TIPO_TUTOR
        public const string CREAR_PROGRAMA_TUTOR_TIPO_TUTOR = "TUTOR_PROGRAM_TYPE_INSERTAR_INSERT";
        public const string LISTAR_PROGRAMA_TUTOR_TIPO_TUTOR = "TUTOR_PROGRAM_TYPE_LISTAR_SELECT";

        //ESTUDIANTE-PROGRAMA-no funciona
        public const string CREAR_ESTUDIANTE_PROGRAMA = "STUDENT_PROGRAM_INSERTAR_INSERT";
        public const string LISTAR_ESTUDIANTE_PROGRAMA = "STUDENT_PROGRAM_LISTAR_SELECT";

        //COMENTARIO
        public const string CREAR_COMENTARIO = "COMMENT_INSERTAR_INSERT";
        public const string LISTAR_COMENTARIOS = "COMMENT_LISTAR_SELECT";
        public const string ACTUALIZAR_COMENTARIO = "COMMENT_ACTUALIZAR_UPDATE";
        public const string ELIMINAR_COMENTARIO = "COMMENT_ELIMINAR_DELETE";


        //FILE
        public const string CREAR_ARCHIVO = "FILE_INSERTAR_INSERT";
        public const string LISTAR_ARCHIVOS = "FILE_LISTAR_SELECT";
        public const string ACTUALIZAR_ARCHIVOS = "FILE_ACTUALIZAR_UPDATE";
        public const string ELIMINAR_ARCHIVO = "FILE_ELIMINAR_DELETE";
        public const string REACTIVAR_ARCHIVO = "FILE_ACTIVAR_UPDATE";
        public const string INSERTAR_ARCHIVO = "InsertarArchivo";
        public const string LISTAR_ARCHIVOS_ID_RESULTADO_TIPO = "FILES_LISTAR_POR_ID_RESULTADOCITA_TIPOPRIVACIDAD_SELECT";

        //AGREGAR_CITA
        public const string AGREGAR_CITA = "APPOINTMENT_INSERTAR_INSERT";
        public const string OBTENER_ID_STUDENT_PROGRAM = "GetStudentProgramId";

        //LISTAR_CITA
        public const string LISTAR_CITA_POR_TUTOR = "APPOINTMENT_LISTARXTUTOR_GRUPAL_SELECT";
        public const string LISTAR_CITA_POR_TUTOR_POR_ALUMNO = "APPOINTMENT_LISTARXTUTORXALUMNO_SELECT";
        //APPOINTMENT_LISTARXID_SELECT
        public const string LISTAR_ALUMNOS_POR_ID_CITA = "APPOINTMENT_LISTARXID_SELECT";

        public const string LISTAR_CITA_POR_ALUMNO = "APPOINTMENT_LISTARXALUMNO_X_ID_SELECT";
        //APPOINTMENT_LISTARXALUMNO_X_ID_SELECT

        //CANCELAR CITa
        public const string CANCELAR_CITA = "APPOINTMENT_CANCEL";

        //ACTUALIZAR ESTADO CITA UpdateAppointmentStatus
        public const string ACTUALIZAR_ESTADO_CITA = "UpdateAppointmentStatus";


        //DERIVATION
        public const string CREAR_DERIVACION = "DERIVATION_INSERTAR_INSERT";
        public const string LISTAR_DERIVACIONES = "DERIVATION_LISTAR_SELECT";
        public const string ACTUALIZAR_DERIVACION = "DERIVATION_ACTUALIZAR_UPDATE";
        public const string ELIMINAR_DERIVACION = "DERIVATION_ELIMINAR_DELETE";
        public const string LISTAR_UNIDADES_DERIVACION = "UNITDERIVATION_LISTAR_SELECT";
        public const string SELECCIONAR_DERIVATION_ID_CITA = "DERIVATION_SELECCIONAR_X_ID_CITA_SELECT";
        public const string SELECCIONAR_DERIVATION_POR_ID_TUTOR = "DERIVATION_LISTAR_POR_ID_TUTOR_SELECT";
        //DERIVATION_LISTAR_POR_ID_TUTOR_SELECT

        //RESULTADO-CITA CON COMENTARIOS
        public const string INSERTAR_RESULTADO_CITA= "APPOINTMENTRESULT_INSERTAR_INSERT"; 
        public const string ACTUALIZAR_RESULTADO_CITA = "APPOINTMENTRESULT_ACTUALIZAR_UPDATE";
        public const string CONSULTAR_RESULTADO_CITA = "APPOINTMENTRESULT_CONSULTAR";
        public const string CONSULTAR_COMENTARIOS_X_ID_RESULTADO_CITA = "COMMENT_CONSULTAR_POR_ID_APPOINMENT_RESULT";
        public const string ACTUALIZAR_COMMENT_X_ID = "COMMENT_ACTUALIZAR_X_ID_UPDATE";
        public const string ACTUALIZAR_RESULTADO_CITA_GRUPAL = "APPOINTMENTRESULT_ACTUALIZAR_GRUPAL_UPDATE";

        //DISPONIBILIDAD TUTOR
        public const string LISTAR_DISPONIBILIDADES_X_TUTOR = "AVAILABILITYTUTOR_LISTARXTUTOR_SELECT";
        public const string ELIMINAR_DISPONIBILIDAD = "AVAILABILITYTUTOR_ELIMINAR_DELETE";
        public const string CREAR_DISPONIBILIDAD = "AVAILABILITYTUTOR_INSERTAR_INSERT";


        //TUTOR_STUDENT_PROGRAM
        public const string CREAR_TUTOR_STUDENT_PROGRAM = "TUTOR_STUDENT_PROGRAM_INSERTAR_INSERT";
        public const string CONSEGUIR_TUTOR_STUDENT_PROGRAM = "TUTOR_STUDENT_PROGRAM_Conseguir_FIND";
        public const string LISTAR_SOLICITUDES_POR_FACULTAD = "TUTOR_STUDENT_PROGRAM_LISTARXFACULTAD_SELECT";
        public const string LISTAR_TUTOR_STUDENT_PROGRAM = "TUTOR_STUDENT_PROGRAM_LISTAR";

        //INDICADORES TUTOR
        public const string LISTAR_CONTADOR_PROGRAMAS_POR_TUTOR = "TUTOR_TUTORINGPROGRAMS_LISTARXTUTOR_SELECT";

        public const string LISTAR_PROGRAMAS_POR_TUTOR = "TUTOR_TUTORINGPROGRAMSBYTUTOR_LISTAR_SELECT";

        public const string LISTAR_CANTIDAD_CITAS_TUTOR = "TUTOR_APPOINTMENTS_STATUS_COUNT_SELECT";


        //NOTIFICACIONES

        public const string LISTAR_NOTIFICACIONES_POR_USUARIO = "NOTIFICATION_LISTARXUSERACOUNT_SELECT"; 


        public const string LISTAR_TUTOR_FECHA_PROGRAMA = "TUTOR_LISTAR_PROGRAMS_SELECT";

        public const string LISTAR_TUTOR_FECHA_CITA = "TUTOR_LISTAR_APPOINTMENTS_SELECT";

        public const string LISTAR_CANT_PROGRAM_VIRTUAL_FACE = "TUTOR_PROGRAM_VIRTUAL_FACE_SELECT";

        //INDICADORES ALUMNO
        public const string LISTAR_CONTADOR_PROGRAMAS_POR_ALUMNO = "STUDENT_STUDENTPROGRAMS_LISTARXSTUDENT_SELECT";

        public const string LISTAR_PROGRAMAS_POR_ALUMNO = "STUDENT_STUDENTPROGRAMSBYSTUDENT_LISTAR_SELECT";

        public const string LISTAR_CANTIDAD_CITAS_ALUMNO = "STUDENT_APPOINTMENTS_STATUS_COUNT_SELECT";

        public const string LISTAR_ALUMNO_FECHA_PROGRAMA = "STUDENT_LISTAR_PROGRAMS_SELECT";

        public const string LISTAR_ALUMNO_FECHA_CITA = "STUDENT_LISTAR_APPOINTMENTS_SELECT";

        public const string LISTAR_ALUMNO_CANT_PROGRAM_VIRTUAL_FACE = "TUTOR_PROGRAM_VIRTUAL_FACE_SELECT";


    }
}
